version: "3"

# TR first attempt at p0lr/PAN-AF as a container 
services:
  panaf:
    container_name: panaf
    hostname: panaf1
    image: panse/panaf
    ports:
      - "81:80/tcp"

    # Volumes store your data between container upgrades
    volumes:
       - './var-autoback/:/var/autoback'
       - './var-dug/:/var/dug'
    restart: unless-stopped
